
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/carry_harder/development
  
test:
  <<: *default
  database: db/carry_harder/test

production:
  <<: *default
  database: db/carry_harder/production
