
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: carry_harder_dev

test:
  <<: *default
  database: carry_harder_test

production:
  <<: *default
  database: carry_harder_prod
